Citizen.CreateThread(function()
    -- First blip
    Mines = AddBlipForCoord(2958.5, 2746.12, 43.48)
    SetBlipSprite (Mines, 618)
    SetBlipDisplay(Mines, 4)
    SetBlipScale  (Mines, 0.8)
    SetBlipAsShortRange(Mines, true)
    SetBlipColour(Mines, 47)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName("Mines")
    EndTextCommandSetBlipName(Mines)
    
    -- Second blip
    WashStones = AddBlipForCoord(1903.09, 268.41, 161.63)
    SetBlipSprite (WashStones, 456)
    SetBlipDisplay(WashStones, 4)
    SetBlipScale  (WashStones, 0.8)
    SetBlipAsShortRange(WashStones, true)
    SetBlipColour(WashStones, 3)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName("Stone Wash")
    EndTextCommandSetBlipName(WashStones)
    
    -- Third blip
    Smelter = AddBlipForCoord(1108.91, -2008.57, 30.97)
    SetBlipSprite (Smelter, 464)
    SetBlipDisplay(Smelter, 4)
    SetBlipScale  (Smelter, 0.8)
    SetBlipAsShortRange(Smelter, true)
    SetBlipColour(Smelter, 5)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName("Smelter")
    EndTextCommandSetBlipName(Smelter)
end)
